services:
    web:
        build:
            context: .
            dockerfile: ./server/web/Dockerfile-dev
        volumes:
            - .:/app
            - /app/node_modules
        container_name: cashly_app
        restart: always
        stdin_open: true
        tty: true
        command: ['yarn', 'dev']
