services:
    web:
        build:
            context: .
            dockerfile: ./server/web/Dockerfile-dev
        volumes:
            - .:/app
            - /app/node_modules
        container_name: cashly_app
        restart: always
        ports:
            - '9000:9000'
        command: ['yarn', 'dev']
