export const AccountColors = {
    PASTELPINK: '#ffd1dc',
    PASTELPEACH: '#ffdab9',
    PASTELORANGE: '#ffb347',
    PASTELYELLOW: '#fdfd96',
    PASTELCREAM: '#fffdd0',
    PASTELAPRICOT: '#fad6a5',
    PASTELLAVENDER: '#e6e6fa',
    PASTELLILAC: '#c8a2c8',
    PASTELPURPLE: '#b39eb5',
    PASTELMAUVE: '#efc0fe',
    PASTELBLUE: '#aec6cf',
    PASTELPOWDERBLUE: '#b0e0e6',
    PASTELPERIWINKLE: '#cfcfff',
    PASTELTURQUOISE: '#a0e6ef',
    PASTELMINT: '#baffc9',
    PASTELGREEN: '#77dd77',
    PASTELLIME: '#dfff00',
    PASTELBEIGE: '#f5f5dc',
    PASTELROSE: '#ffcbdb',
    PASTELBROWN: '#c3b091',
};
