name: Deploy to Firebase Hosting on merge

on:
    push:
        branches:
            - master

jobs:
    # Job для проверки ESLint
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # Установка зависимостей
            - name: Install dependencies
              run: npm ci

            # Шаг проверки ESLint
            - name: Run ESLint
              run: npm run lint

    # Job для деплоя
    deploy:
        runs-on: ubuntu-latest
        needs: lint # Зависимость от результата lint
        steps:
            - uses: actions/checkout@v4

            # Установка зависимостей (повторно, если требуется)
            - name: Install dependencies
              run: npm ci

            # Сборка
            - name: Build PWA
              run: npm run build:pwa

            # Деплой
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CASHLY_APP_1215E }}
                  channelId: live
                  projectId: cashly-app-1215e
